# Generated by Django 4.2 on 2023-12-24 08:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siparis', '0001_initial'),
        ('urun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrunSiparis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adet', models.IntegerField(default=0)),
                ('fiyat', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 12, 24, 11, 28, 6, 493729), editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='siparis.siparis')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='urun.urun')),
            ],
            options={
                'db_table': 'urun_siparis',
            },
        ),
    ]
