# Generated by Django 4.2 on 2023-12-24 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 11, 28, 59, 661053), editable=False),
        ),
    ]
